// Package configfile persists non-secret desktop configuration atomically.
package configfile

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/pawel/qobuz-curator/internal/config"
	"go.yaml.in/yaml/v3"
)

// Load reads only path and built-in defaults. Environment overrides are
// deliberately excluded so desktop migration cannot persist injected secrets.
func Load(path string) (config.Config, error) {
	cfg, err := config.Initial()
	if err != nil {
		return config.Config{}, err
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		return config.Config{}, fmt.Errorf("read configuration: %w", err)
	}
	if err = yaml.Unmarshal(raw, &cfg); err != nil {
		return config.Config{}, fmt.Errorf("decode configuration: %w", err)
	}
	if err = cfg.Validate(); err != nil {
		return config.Config{}, fmt.Errorf("invalid configuration: %w", err)
	}
	return cfg, nil
}

// Save writes cfg with user-only permissions and atomically replaces path.
func Save(path string, cfg config.Config) error {
	cfg.QobuzUserToken, cfg.OpenAIAPIKey = "", ""
	if err := cfg.Validate(); err != nil {
		return fmt.Errorf("invalid configuration: %w", err)
	}
	raw, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("encode configuration: %w", err)
	}
	raw = append([]byte("# Generated by Qobuz Curator. Credentials are stored in the operating-system vault.\n"), raw...)
	directory := filepath.Dir(path)
	if err = os.MkdirAll(directory, 0700); err != nil {
		return fmt.Errorf("create configuration directory: %w", err)
	}
	temporary, err := os.CreateTemp(directory, ".qobuz-curator-config-*.tmp")
	if err != nil {
		return fmt.Errorf("create temporary configuration: %w", err)
	}
	temporaryPath := temporary.Name()
	defer func() {
		_ = temporary.Close()
		_ = os.Remove(temporaryPath)
	}()
	if err = temporary.Chmod(0600); err != nil && !errors.Is(err, os.ErrPermission) {
		return fmt.Errorf("protect temporary configuration: %w", err)
	}
	if _, err = temporary.Write(raw); err == nil {
		err = temporary.Sync()
	}
	if closeErr := temporary.Close(); err == nil {
		err = closeErr
	}
	if err != nil {
		return fmt.Errorf("write temporary configuration: %w", err)
	}
	if err = os.Rename(temporaryPath, path); err != nil {
		return fmt.Errorf("replace configuration atomically: %w", err)
	}
	if err = os.Chmod(path, 0600); err != nil && !errors.Is(err, os.ErrPermission) {
		return fmt.Errorf("protect configuration: %w", err)
	}
	return nil
}
